on: push
name: 🚀 Deploy
jobs:
  web-deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v2
      - name: 🚀 FTP Upload
        uses: SamKirkland/FTP-Deploy-Action@a9644610a0efe63542b1887c9317ce8628f56521 # 4.2.0
        with:
          server: ftp.swharden.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./src/
          server-dir: /software/NernstCalc/
          log-level: minimal
      - name: 🧹 Purge Cache
        run: curl --user deploy:${{ secrets.CACHE_PASSWORD }} https://swharden.com/admin/clear-cache.php
